services:
  cardio-ai-portal-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cardio-ai-portal-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    restart: unless-stopped
